"""Tests for SEO topics autogenerate endpoint.

Validates:
- Topic discovery integration
- Duplicate filtering
- Response model
"""

from datetime import datetime

import pytest

from backend.api.seo.routes import (
    SeoTopic,
    SeoTopicsAutogenerateResponse,
)
from backend.services.topic_discovery import Topic


@pytest.mark.unit
class TestSeoTopicsAutogenerateResponse:
    """Test SeoTopicsAutogenerateResponse model."""

    def test_empty_response(self):
        """Empty response is valid."""
        resp = SeoTopicsAutogenerateResponse(topics=[], count=0)
        assert len(resp.topics) == 0
        assert resp.count == 0

    def test_response_with_topics(self):
        """Response with topics is valid."""
        topic = SeoTopic(
            id=1,
            keyword="AI decision making",
            status="researched",
            source_analysis_id=None,
            notes="Explore how AI tools help leaders make decisions",
            created_at=datetime.now(),
            updated_at=datetime.now(),
        )
        resp = SeoTopicsAutogenerateResponse(topics=[topic], count=1)
        assert len(resp.topics) == 1
        assert resp.count == 1
        assert resp.topics[0].keyword == "AI decision making"


@pytest.mark.unit
class TestTopicDiscoveryIntegration:
    """Test topic discovery service returns expected format."""

    def test_topic_dataclass_fields(self):
        """Topic dataclass should have required fields."""
        topic = Topic(
            title="Test Topic",
            description="Test description",
            keywords=["keyword1", "keyword2"],
            relevance_score=0.85,
            source="context",
        )
        assert topic.title == "Test Topic"
        assert topic.description == "Test description"
        assert len(topic.keywords) == 2
        assert topic.relevance_score == 0.85
        assert topic.source == "context"

    def test_topic_source_values(self):
        """Topic source should be one of expected values."""
        valid_sources = ["context", "trend", "gap"]
        for source in valid_sources:
            topic = Topic(
                title="Test",
                description="Desc",
                keywords=[],
                relevance_score=0.5,
                source=source,
            )
            assert topic.source == source


@pytest.mark.unit
class TestAutogenerateDuplicateFiltering:
    """Test duplicate topic filtering logic."""

    def test_filter_existing_keywords_case_insensitive(self):
        """Duplicate check should be case-insensitive."""
        existing_keywords = ["ai tools", "machine learning"]
        discovered = [
            Topic(
                title="AI Tools",  # Should be filtered (case-insensitive match)
                description="Desc1",
                keywords=[],
                relevance_score=0.9,
                source="context",
            ),
            Topic(
                title="New Topic",  # Should NOT be filtered
                description="Desc2",
                keywords=[],
                relevance_score=0.8,
                source="trend",
            ),
        ]

        # Apply same filtering logic as the endpoint
        new_topics = [t for t in discovered if t.title.lower() not in existing_keywords]

        assert len(new_topics) == 1
        assert new_topics[0].title == "New Topic"

    def test_empty_existing_keywords(self):
        """All topics should pass if no existing keywords."""
        existing_keywords: list[str] = []
        discovered = [
            Topic(
                title="Topic 1",
                description="Desc1",
                keywords=[],
                relevance_score=0.9,
                source="context",
            ),
            Topic(
                title="Topic 2",
                description="Desc2",
                keywords=[],
                relevance_score=0.8,
                source="trend",
            ),
        ]

        new_topics = [t for t in discovered if t.title.lower() not in existing_keywords]

        assert len(new_topics) == 2
